### ISSUE TITLE
v7.8.2 breaks videojs-contrib-eme

### ISSUE THREAD

**Issue by vgrafe** [videojs/video.js#6720]
## Description
A straightforward implementation using videojs-contrib-eme to decrypt the chunks received works on v7.7.6 but not on v7.8.2.

Tested on Chrome only so far. when running exactly the same code, the following happens:
- When using v7.7.6: licences are requested, received, the stream is played as expected
- When using 7.8.2, the call to `player.eme()` throws: `player.eme() is not a function`.

I could not try the version that were released between 7.7.6 and 7.8.2, so the title for this issue might be misleading.

Let me know if there's any more info I should add.

**Comment by gkatsev** [comment]
Have a live example? I've been able to get it working locally with latest Video.js.
If you can't share it publicly but can still share it privately, feel free to ping me on slack.

**Comment by vgrafe** [comment]
Here is the exact code we have running. I said straightforward, but this is in the context of a react/nextjs webapp.

```js
import('video.js').then(function ({ default: videojs }) {
        import('videojs-contrib-eme').then(function () {
          const videoNode = document.getElementById('video-elt' + id);
          if (!videoNode || !manifest) return;

          player.current = videojs(
            videoNode,
            function () {
              try {
                if (manifest.keySystems) {
                  console.log('encrypted media, getting licence...');
                  player.current.eme();
                }
              } catch (e) {
                console.error(e);
                onError && onError(e);
              }

              player.current.src(manifest);
              onLoaded && onLoaded(player.current);

              autoPlay && player.current.play();
            }
          );
        });
      });```

The top lines dynamically import videojs and eme in order to not have them packed in the main js bundle.

Thank you for your help!

**Comment by vgrafe** [comment]
And [here's ](https://gist.github.com/vgrafe/2d6630d2758f83c3f5ee0b210db3cc20)a gist with the whole file. Figured it would help to have more context that the code above, esp since it runs into an useEffect hook.

**Comment by gkatsev** [comment]
I can confirm that I can get eme working with video.js 7.8.3, see https://videojs-http-streaming.netlify.app/?debug=false&autoplay=false&muted=false&minified=false&liveui=false&partial=false&url=https%3A%2F%2Famssamples.streaming.mediaservices.windows.net%2F622b189f-ec39-43f2-93a2-201ac4e31ce1%2FBigBuckBunny.ism%2Fmanifest(format%3Dmpd-time-csf)&type=application%2Fdash%2Bxml&keysystems=%7B%0A%20%20%22com.widevine.alpha%22%3A%20%22https%3A%2F%2Famssamples.keydelivery.mediaservices.windows.net%2FWidevine%2F%3FKID%3D1ab45440-532c-4399-94dc-5c5ad9584bac%22%2C%0A%20%20%22com.microsoft.playready%22%3A%20%22https%3A%2F%2Famssamples.keydelivery.mediaservices.windows.net%2FPlayReady%2F%22%0A%7D

Unfortunately, I'm not too familiar with useEffect or react hooks yet. Anything else change on your end? Or just updating of Video.js?

**Comment by vgrafe** [comment]
Nothing changed except for the version pulled for videojs. I'll have to check either the source for eme or troubleshoot how webpack imports it, maybe there are some expectations on how or when the library is loaded.

**Comment by gkatsev** [comment]
It seems like everything should work as eme is loaded after videojs and before the player is initialized.
One thing that I can imagine is that the version of videojs that your app and eme depend upon end up being different.

**Comment by vgrafe** [comment]
> One thing that I can imagine is that the version of videojs that your app and eme depend upon end up being different.

I don't understand how, can you elaborate? the relevant lines in package.json dependencies are
```
    "video.js": "7.7.6",
    "videojs-contrib-eme": "3.7.0"
```
with the eme call throwing when video.js version set at 7.8.2.

Also I just tried your link, the video does not load when I try it. Seems like the url to the manifest expired.
