### ISSUE TITLE
TypeError on Tizen 2.4 since 7.12.2

### ISSUE THREAD

**Issue by JeppeTh** [videojs/video.js#7245]
## Description
I get this when running on Tizen 2.4 since 7.12.2
TypeError: 'undefined' is not a function (evaluating 't[t=n](e.reduce(Yi(t),i))')

Don't think I can get more info than that...

**Comment by JeppeTh** [comment]
O see that formatting of above post made it a bit confusing, but I guess this.tech_ is undefined and t[] then fails... I.e. 
**t = this.tech_, i = r, t[t = n](**

            }, e.techCall_ = function(n, r) {
                this.ready(function() {
                    if (n in Xi) return e = this.middleware_, t = this.tech_, i = r, t[t = n](e.reduce(Yi(t), i));
                    if (n in Ki) return zi(this.middleware_, this.tech_, n, r);
                    var e, t, i;
                    try {
                        this.tech_ && this.tech_[n](r)
                    } catch (e) {
                        throw m(e), e
                    }
                }, !0)

**Comment by JeppeTh** [comment]
Nah - that was not it. I don't get what the problem is - but things like setVolume, setCurrentTime ends up in the e.reduce part which doesn't work:
TypeError: 'undefined' is not a function (evaluating 't[t = n](e.reduce(Gi(t), i))')'

I don't get what is undefined though...

(n in Wi): true 
(n in zi): false 
e.reduce: function reduce() {    [native code]}
Gi: function Gi(i) {return function(e,t){return e===ji?ji:t[i]?t[i](e):e}}
t[t=n]: function (e) {try{this.isScrubbing_&&this.el_.fastSeek&&W?this.el_.fastSeek(e):this.el_.currentTime=e}catch(e){f(e,"Video is not ready. (Video.js)")}}

Using VHS btw...

**Comment by brandonocasey** [comment]
Does this happen with the unminified bundle? If it does that might help you diagnose the issue.

**Comment by JeppeTh** [comment]
Thx for the suggestion - it actually works with the non-min version.
What is the difference with the min version really? Never understood that - only less size or also more functionality etc?

**Comment by JeppeTh** [comment]
But these two issues are not related? 

Also I believe this issue also happens on Tizen 5.5 - but the http-streaming version from the other issue works on 5.5.
