### ISSUE TITLE
HEPL!! Problems in the work of the plug-in with the player version v7.0.3

### ISSUE THREAD

**Issue by inerc** [videojs/video.js#5261]
Hi, I updated the player version. And I had a mistake.
```javascript
constructor(player: Player, options: Options) {
    super(player, options)
    this.options = options
    const qualityLevels = player.qualityLevels()
    this.quality = []
    qualityLevels.on('addqualitylevel', event => {
      this.quality.push(event.qualityLevel)
      this.update()
    })
  }```

Error:
`player.qualityLevels() undefined`
I can not find the cause of the problem. help me please

**Comment by BrandonOCasey** [comment]
seems like you may be missing the qualityLevels plugin on the page or in a require statement in your code.

**Comment by gkatsev** [comment]
Are you using npm and bundler like webpack or browserify? quality-levels doesn't have v7 as a valid dependency yet. We have a PR to fix it https://github.com/videojs/videojs-contrib-quality-levels/pull/39

**Comment by gkatsev** [comment]
Closing this in favor of https://github.com/videojs/videojs-contrib-quality-levels/issues/40

**Comment by dylanjha** [comment]
Still having issues with videojs-contrib-quality-levels (2.0.5) and video.js 7.0.5

When I look at `videojs.getPlugins()` the qualityPicker plugin is there, but `player.qualityLevels()` is not a function. @inerc with the latest 2.0.5 release is the quality levels plugin working for you now?

**Comment by dylanjha** [comment]
Disregard. I realized I was double-loading video.js b/c of other plugin dependencies. Confirmed this works with videojs 7.0.3 👍

**Comment by gkatsev** [comment]
Thanks for confirming @dylanjha!

**Comment by inerc** [comment]
@gkatsev @dylanjha @BrandonOCasey 
Thanks a lot guys all works fine.
videojs 7.0.5
videojs-contrib-quality-levels 2.0.5
