### ISSUE TITLE
Uncaught TypeError: this.el_.vjs_getProperty is not a function

### ISSUE THREAD

**Issue by lomok** [videojs/video.js#2755]
When using the new 5.0.0 I get this:

Uncaught TypeError: this.el_.vjs_getProperty is not a function

When I run it locally , I do not get this. Any ideas?
I am running it inside Inkling Habitat system.

It happens when it first starts up - I am writing the video tag into a div.

So, I never see anything before it crashes.

buffered @ video.js:10008(anonymous function) @ video.js:11283bufferedPercent @ video.js:11274(anonymous function) @ video.js:11250ret @ video.js:13562ret @ video.js:13562
mhe-video-main.js:56 XHR finished loading: &timestamp=1446054119219".checkForConnection @ mhe-video-main.js:56(anonymous function) @ video-main.js:241j @ jquery-2.1.1.min.js:2k.fireWith @ jquery-2.1.1.min.js:2n.extend.ready @ jquery-2.1.1.min.js:2I @ jquery-2.1.1.min.js:2

**Comment by lomok** [comment]
Resolved -

**Comment by gkatsev** [comment]
@lomok can you ask you to elaborate on what the issue was and how it was resolved? Might be helpful to others. Thanks!

**Comment by samward1985** [comment]
@lomok seconding @gkatsev !

**Comment by joseym** [comment]
@lomok doesn't seem inclined, but yes - I'd like to know how I can resolve this issue.

**Comment by lomok** [comment]
Hi - I have been off this project and now am back - sorry for the delay.

This error corrected itself when we upgraded to 5.0. We had actually fixed it in an earlier version
by finding the line where the fault occurred in the videojs code and commenting something out (I cannot find what we did exactly=lost the build)- but that worked as well. Seems like it was exoecting something and not getting it. Commenting it out caused no problems.

There have been some reports that it has reoccurred with 5.02, so I will post if this is happening and try to find the solution we came up with.

**Comment by colabora001** [comment]
happen in 5.7.1

**Comment by colabora001** [comment]
video.js:14187 Uncaught TypeError: this.el_.play is not a functionplay @ video.js:14187techCall_ @ video.js:10576play @ video.js:10632handleClick @ video.js:2689ret @ video.js:18962data.dispatcher @ video.js:18610

**Comment by mister-ben** [comment]
A reduced test case with steps to reproduce would help understand what the issue is.
