### ISSUE TITLE
Flash fallback for .mp4 files not working in Firefox 21 on 10.8

### ISSUE THREAD

**Issue by chrisballinger** [videojs/video.js#566]
[23:02:04.345] TypeError: this.b.vjs_play is not a function @ https://vjs.zencdn.net/4.0.3/video.js:90

Example here: https://openwatch.net/w/raw

Works fine in Safari and Chrome

We don't have WebM versions of our videos so we were hoping that the flash fallback would suffice...

I tried setting the techOrder to html, flash as well in the dynamic setup but it didn't seem to work.
