### ISSUE TITLE
this[key] is not a function on vjs 4.5.1

### ISSUE THREAD

**Issue by Globulopolis** [videojs/video.js#1125]
I got this error after update from 4.4.3 to latest stable:

Timestamp: 02.04.2014 15:01:49
Error: TypeError: this[key] is not a function
Source File: http://10.10.10.2/components/assets/players/videojs/video.dev.js
Line: 2912

What's wrong?
