### ISSUE TITLE
Dom.isReal not a function Error

### ISSUE THREAD

**Issue by aljibbs** [videojs/video.js#4331]
## Description
I have tried using videojs with ionic typescript and things don't work out. I keep getting an error.

## Steps to reproduce
1. npm install @types/videojs --save
2. import videojs from 'video.js';
3. let v = videojs(document.getElementById('vPlayer'));

### Expected
Video player should be rendered

### Actual
Error page displays

### Error output
Dom.isReal is not a function

#### videojs
6.0.1
#### browsers
Chrome
#### OSes
Windows

**Comment by gkatsev** [comment]
Hm... interesting. Would you be able to provide a reduced test case? `Dom.isReal` was introduced in 5.16.0 which is what `@types/videojs` is built against.

**Comment by aljibbs** [comment]
What I am trying to do is use the library with the ionic framework so after installing, i import the library and call the videojs() function with the video element as argument as presented in the videojs docs on the main site.

// importing the library from node_modules
import videojs from 'videojs';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
         // video element reference
  @ViewChild('vPlayer') videoPlayer: ElementRef;

  constructor(public navCtrl: NavController) {
      let vp = videojs(this.videoPlayer);
           vp.play();
  }
}

**Comment by aljibbs** [comment]
Edited as a reduced test case.

**Comment by gkatsev** [comment]
Can I ask how you're bundling up the code?

**Comment by gkatsev** [comment]
If you're using rollup, I just ran into a similar issue. I think I have a solution to it.

**Comment by aljibbs** [comment]
I am using the library with the ionic framework so I think it's webpack. Can I see your solution though

**Comment by gkatsev** [comment]
If I'm reading [this](https://github.com/driftyco/ionic-app-scripts#overriding-config-values) correctly, it defaults to the webpack bundler but can use rollup. Though, [it can be changed](https://github.com/driftyco/ionic-app-scripts#packagejson-config).

The current solution I have is to move this line https://github.com/videojs/video.js/blob/master/src/js/video.js#L24 to be the first import that isn't from `global`. Seems to be working locally with that fix. I'll probably PR it tomorrow. I'll also be finishing [this project](https://github.com/videojs/videojs-bundler-sample) tomorrow which exactly is for showing how videojs can be used with different bundlers.

**Comment by gkatsev** [comment]
This will potentially be fixed when https://github.com/videojs/video.js/pull/4363 is released.

**Comment by aljibbs** [comment]
After following your fix, I end up with a new error.

Cannot find module "safe-json-parse/tuple"

**Comment by gkatsev** [comment]
Not sure what else can be done here. Does it work in newer versions like 6.5 or 6.4? We haven't had any issues with bundling beyond that original fix.
