### ISSUE TITLE
Changing the source of the video

### ISSUE THREAD

**Issue by chaitanyapro** [videojs/video.js#2246]
I'm trying to change the source of the video using:

videojs('sortedd', {}, function(){
      this.src({ type: "video/mp4", src: 'questions/question_1/Q394Correct.mp4' });
      this.play();
});

But I'm getting this warning in the console.
VIDEOJS: WARN: Player "sortedd" is already initialised. Options will not be applied.

Can you please tell me what's the right way of changing the source of the video. Is it okay to ignore this warning?

**Comment by mister-ben** [comment]
There are a couple of ways to initialise the player: include `data-setup='{}'` in your player embed, or use `videojs(id, options, ready)`.

If you use the latter and the player is already set up (because you used `data-setup`) the ready function is executed but the warning is shown to make it clear any options included here haven't been applied. It's not a problem in this case because your options are empty (`{}`).

You can rewrite this a couple of ways.

```js
videojs('sortedd').ready(function(){ … });
```

```js
var player = videojs('sortedd');
player.src({ … });
player.play();
```

**Comment by chaitanyapro** [comment]
Thank you :) this is exactly what I was looking for.

**Comment by oleynikd** [comment]
Does this work with v5?
I get this:
```
TypeError: this.el_.play is not a function. (In 'this.el_.play()', 'this.el_.play' is undefined)
```

**Comment by mmcc** [comment]
@oleynikd Yes, [it still works](http://jsbin.com/pedosotohi/edit?html,output).

**Comment by junerockwell** [comment]
This suggestion doesn't work in version 6.2.5.
````
var plr = videojs("my-video", {
    source: {
      type: 'video/mp4',
      src: 'https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.mp4'
    }
  }, function onPlayerReady() {
    console.log("onPlayerReady()")
    // this.load();
    this.src = {
    type: 'video/mp4',
    src: 'https://cdn.selz.com/plyr/1.5/View_From_A_Blue_Moon_Trailer-HD.mp4'
  };
    this.play();
  });
````
![screen shot 2017-08-30 at 9 25 46 am](https://user-images.githubusercontent.com/5051574/29883448-32c2baf6-8d65-11e7-8c15-902f8707d439.png)
