### ISSUE TITLE
External plugins are not working since version 7.11.0

### ISSUE THREAD

**Issue by lunika** [videojs/video.js#7091]
## Description

I'm trying to upgrade from version 7.10.2 to version 7.11.4 but my code is not working anymore. 
The problem is with external plugins. I'm using plugins [videojs-http-source-selector](https://github.com/jfujita/videojs-http-source-selector) and [videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels) to have a quality selector in the UI.

Since version 7.11.0 both plugins are not registered anymore. If I force to register them calling explicitly `videojs.registerPlugin` in my module they are registered but then I have error about non existing MenuComponent registered in the `videojs-http-source-selector` plugin.

In my module I [first import](https://github.com/openfun/marsha/blob/ddc13a03be7345a44c800f49084659600c8272d0/src/frontend/Player/createVideojsPlayer.ts#L3-L4) them, then I create an [instance of videojs](https://github.com/openfun/marsha/blob/ddc13a03be7345a44c800f49084659600c8272d0/src/frontend/Player/createVideojsPlayer.ts#L26-L44) and at this time I have an error telling me that the plugin `httpSourceSelector` does not exists.

My code was working like this in version 7.10.2 of videojs. I follow both plugins documentation to setup them.

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs
what version of videojs does this occur with? 7.11.0 and above
### plugins
are any videojs plugins being used on the page? If so, please list them below.
videojs-http-source-selector: 1.1.6
videojs-contrib-quality-levels: 2.0.9

The project is in typescript (4.1.5) and built using webpack (5.21.2)

Thanks for your help

**Comment by gkatsev** [comment]
Thanks for opening the issue, we'll definitly take a look.

**Comment by lunika** [comment]
For your information, I wrote a plugin recently, hosted in the same project using videojs and this plugin is registered well with videojs 7.11

The plugin is [here](https://github.com/openfun/marsha/tree/d0da96eefbf2e1104e893d29fad7567d689883c6/src/frontend/Player/videojs/qualitySelectorPlugin) and is registered [here ](https://github.com/openfun/marsha/blob/d0da96eefbf2e1104e893d29fad7567d689883c6/src/frontend/Player/createVideojsPlayer.ts#L5) and enabled if needed using the [options](https://github.com/openfun/marsha/blob/d0da96eefbf2e1104e893d29fad7567d689883c6/src/frontend/Player/createVideojsPlayer.ts#L53-L59).

**Comment by gkatsev** [comment]
@lunika interesting, so, that other plugin is being registered fine but quality-levels isn't?

**Comment by lunika** [comment]
Yes, my plugin developed in the same project is registered but not videojs-http-source-selector and videojs-contrib-quality-levels

**Comment by gkatsev** [comment]
Thanks, that's helpful to try and narrow things down!

**Comment by onhate** [comment]
I'm facing the same issue

**Comment by cboissel-onf** [comment]
Same issue here

**Comment by cviktor** [comment]
I had the same issue in an Angular app when I tried to integrate VideoJS and added the [videojs-contrib-quality-levels](https://github.com/videojs/videojs-contrib-quality-levels) plugin. It seems that the `registerPlugin` is called by the plugin but the function that is passed in the `registerPlugin` parameter is never called. My solution was to call the `registerPlugin` by hand. I am using the same versions as in the original comment.

**Comment by lunika** [comment]
I was working on what you ask @gkatsev, I updated first on version 7.11.7 and I have now a different error:
```
Cannot find module '@videojs/vhs-utils/cjs/resolve-url.js' from 'node_modules/video.js/dist/video.cjs.js'
```
Should I open a new issue for this case ?

**Comment by lunika** [comment]
I tried on codesandbox to reproduce this issue but it's working...

If someone else in this ticket issue want to take a look: https://codesandbox.io/s/sad-bird-8n4uc

**Comment by lunika** [comment]
Ok so I have a local version working.
I don't know if it's the case for everybody on this issue but I'm using yarn. Yarn is creating a [`yarn.lock`](https://classic.yarnpkg.com/en/docs/yarn-lock/) file and every week I have a bot updating all my dependencies. This yarn.lock is quite old now.

I removed it to regenerate a fresh one and since I don't have this issue, my code is working with videojs 7.11.4... Can everybody reproduce this ?

But I still the issue related here: https://github.com/videojs/video.js/issues/7091#issuecomment-802890506

**Comment by lunika** [comment]
I made a PR on my project resolving the issue as explain in my last message: https://github.com/openfun/marsha/pull/899

**Comment by gkatsev** [comment]
@lunika good to hear that the main issue went away. As for the `videojs/vhs-utils/cjs/resolve-url`, we saw this locally but theoretically https://github.com/videojs/video.js/pull/7128 should've fixed it.
Seems like it's working ok on the codesandbox if I update to 7.11.7? Though, now I wonder if it's a yarn thing. What's the output of `yarn list @videojs/vhs-utils`? Also, what's the local `node_modules` file structure? Wonder if yarn is putting it into a different place than npm is.
For reference, locally, I have:
```
$ npm ls @videojs/vhs-utils
video.js@7.11.6 /Users/gkatsevman/p/video.js
└─┬ @videojs/http-streaming@2.6.4
  └── @videojs/vhs-utils@3.0.0

**Comment by gkatsev** [comment]
Spoke with @evanfarina as he has a bit more experience with yarn, and he found that, particularly with versions of Video.js that update VHS, he needs to do a little dance to get it working right with the yarn lock file.
He deletes all video.js related packages including Video.js. He confirms that they have been removed from the lock file. Then he re-installs `video.js` and then he re-installs the other packages like `videojs-contrib-quality-levels`.

In addition, this might be related to #7109 in that addressing #7019 could improve things so that you don't need to do any of these shenanigans. It's something we'll investigate.

**Comment by lunika** [comment]
I tried again with version `7.11.8` and it's still failing like in this [comment](https://github.com/videojs/video.js/issues/7091#issuecomment-802890506)

When I list the package installed I have this

```
$ yarn list --pattern videojs
yarn list v1.22.5
├─ @videojs/http-streaming@2.6.4
│  ├─ @videojs/http-streaming@2.4.2
│  │  └─ @videojs/vhs-utils@2.3.0
│  └─ @videojs/vhs-utils@3.0.0
├─ @videojs/vhs-utils@2.3.0
├─ @videojs/xhr@2.5.1
├─ aes-decrypter@3.1.2
│  └─ @videojs/vhs-utils@3.0.0
├─ m3u8-parser@4.5.2
│  └─ @videojs/vhs-utils@3.0.0
├─ mpd-parser@0.15.4
│  └─ @videojs/vhs-utils@3.0.0
├─ videojs-contrib-quality-levels@2.0.9
│  └─ @videojs/http-streaming@2.4.2
├─ videojs-font@3.2.0
├─ videojs-http-source-selector@1.1.6
│  └─ @videojs/http-streaming@2.4.2
└─ videojs-vtt.js@0.15.2
```

There are 2 versions of `@videojs/http-streaming` required. One by `video.js` directly. The other is not a direct dependency. Plugins are requiring `video.js "^6 || ^7"` and last available version of `video.js` is `7.11.4`. Maybe once a new official release will be made I will don't have the issue anymore.

**Comment by lunika** [comment]
A little update.

Version `7.11.8` is now a public release and to update to this version I had to remove first all video.js package installed and then reinstall them. This is the way to upgrade video.js when you use yarn... 

I think we can now close this issue.

Thanks for your help @gkatsev

**Comment by tzarebczan** [comment]
Running yarn remove video.js and then add didn't work here. Trying clearing out the lock file next.
